### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN error when opening another app from the AccountsApp

### ISSUE THREAD

**Issue by tec7z7** [LiveChurchSolutions/AccountsApp#105]
1. [Login](https://accounts.churchapps.org/login) to the AccountsApp.
2. Select the Church tab
3. Select one of the links in the list of apps you have access to open the app in a new tab.
4. The newly opened app might load fine or you might get an error similar to this: 
<img width="772" alt="Screen Shot 2022-02-04 at 2 40 46 PM" src="https://user-images.githubusercontent.com/5470928/152601046-c9ccce02-809a-42d9-b6fa-966cda97b38e.png">
It seems to happen more consistently in a new incognito window.

**Comment by jzongker** [comment]
Completely reworked that app list to be more user friendly and corrected this bug in the process.  https://github.com/LiveChurchSolutions/AccountsApp/commit/88de06980ba57275ff0acc888e5ff14508cb1fad
