### ISSUE TITLE
Don't show Manage Roles/Members to those without access

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AccountsApp#110]
If the user doesn't have both Manage Roles and View People access, don't show the option to edit roles.

**Comment by pranavmalvawala** [comment]
Could you elaborate on this? cause I think it is already like this.

**Comment by PhotoPaul** [comment]
@jzongker 
It currently checks for `Permissions.accessApi.roles.edit`.
Would you like me to change this to `Permissions.accessApi.roles.edit && Permissions.accessApi.users.view`?

**Comment by PhotoPaul** [comment]
Added https://github.com/LiveChurchSolutions/AccountsApp/commit/ca27e34545472415c36617b526bf239cccf6bc57
