### ISSUE TITLE
Church specific access appears to disable server admin access

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AccountsApp#111]
Server admins should have access to view people and manage roles/users on EVERY church.  It appears that works ok until you grant a server admin any permissions to a church.  At that point, the server admin has only the granted permissions and has lost their global edit roles permissions for that church.  Need to track down and correct.

**Comment by PhotoPaul** [comment]
@jzongker I tried different scenarios, but I can't replicate this behavior. I have a clean local installation where I'm the server admin, and I have created 2 churches. Can you please describe (or make a short video) with what additional steps I need to take in order to replicate this? Thank you.

**Comment by jzongker** [comment]
@PhotoPaul - I'm sorry, it appears you are correct.  I'm not sure if I had taken different steps before or another change in the past 23 days fixed this bug, but I consistently have the correct server admin permissions regardless of church specific permissions now.  Closing the issue.
