### ISSUE TITLE
Edit Logo/Colors

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AccountsApp#20]
We need a global interface for churches to configure their logo and colors, for use throughout all of the apps.  I believe the edit church screen in the AccountsApp is the appropriate place for this config.  You can largely copy code from StreamingLiveApp for how to do this.

I think we need the following fields:
- Rectangle Logo (400x100px transparent png).  
- Square Logo (400x400px transparent png)
- Primary Color
- Primary Contrast
- Secondary Color
- Secondary Contrast

As for where to store the data, it's not perfect, but I think the Setttings table (from ApiBase) within the AccessApi.  Even though this isn't directly related to access, the core information about each church is stored here.

Once this is complete, the edit theme section of StreamingLive will be replaced by this and B1 app will also consume this.  I'm hoping we can also use this to white label Chums for churches.

**Comment by jzongker** [comment]
I think we can store the base64 encoded logos directly in the settings table.

**Comment by pranavmalvawala** [comment]
Fixed
