### ISSUE TITLE
Update forgot password email

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AccountsApp#5]
We need to make the email address that the forgot password request comes from be a .env variable, defaulted to support@churchapps.org.

**Comment by pranavmalvawala** [comment]
Fixed by https://github.com/LiveChurchSolutions/ChumsApp/pull/17 https://github.com/LiveChurchSolutions/AccountsApp/pull/7
https://github.com/LiveChurchSolutions/StreamingLiveWeb/pull/1

**Comment by pranavmalvawala** [comment]
Forgot password API has been updated to have a default support email fo sending mails. 
https://github.com/LiveChurchSolutions/AccessApi/pull/11
