### ISSUE TITLE
List of available apps is broken

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/AccountsApp#95]
This your access section no longer works due to eliminating the concept of activating apps for churches.  

![image](https://user-images.githubusercontent.com/1447203/134977429-21558a60-4b76-4adf-863b-dcbf2f6cae21.png)

Let's remove it, but we still need to provide shortcuts for users to get to the apps we offer.  Instead, let's just have a hardcoded list with the app logos and one-line summaries of what they do (the brochure site home pages have descriptions you can use) that a links to get to each of these apps (and logs the user in).

**Comment by pranavmalvawala** [comment]
You are checking on production site but I got the old interface working few days back. Check out staging! If you still want this way, apps with description, let me know.

**Comment by jzongker** [comment]
If I create a new account, I see this.  No way to get to our add b1, chums, etc.  I think we just need to hardcode a list of the apps and their links.

![image](https://user-images.githubusercontent.com/1447203/135921725-aadbd038-bc71-4f94-bf37-06633f58380f.png)
